package com.studentexchange.core.entity;

// Generated 2017-3-13 15:36:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * TbEventlog generated by hbm2java
 */
@Entity
@Table(name = "tb_eventlog", catalog = "studentexchange")
public class TbEventlog implements java.io.Serializable {

	private long tbBaseid2;
	private TbEvent tbEvent;
	private TbUser tbUser;
	private Date createdate;
	private String state;

	public TbEventlog() {
	}

	public TbEventlog(long tbBaseid2, Date createdate) {
		this.tbBaseid2 = tbBaseid2;
		this.createdate = createdate;
	}

	public TbEventlog(long tbBaseid2, TbEvent tbEvent, TbUser tbUser, Date createdate, String state) {
		this.tbBaseid2 = tbBaseid2;
		this.tbEvent = tbEvent;
		this.tbUser = tbUser;
		this.createdate = createdate;
		this.state = state;
	}

	@Id
	@Column(name = "tb__baseid2", unique = true, nullable = false)
	@GeneratedValue(generator = "eventloganswertableGenerator")
	@GenericGenerator(name = "eventloganswertableGenerator", strategy = "increment")
	public long getTbBaseid2() {
		return this.tbBaseid2;
	}

	public void setTbBaseid2(long tbBaseid2) {
		this.tbBaseid2 = tbBaseid2;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "baseid")
	public TbEvent getTbEvent() {
		return this.tbEvent;
	}

	public void setTbEvent(TbEvent tbEvent) {
		this.tbEvent = tbEvent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb__baseid")
	public TbUser getTbUser() {
		return this.tbUser;
	}

	public void setTbUser(TbUser tbUser) {
		this.tbUser = tbUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdate", nullable = false, length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Column(name = "state", length = 20)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
