package com.studentexchange.core.entity;

// Generated 2017-3-13 15:36:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * TbEvent generated by hbm2java
 */
@Entity
@Table(name = "tb_event", catalog = "studentexchange")
public class TbEvent implements java.io.Serializable {

	private long baseid;
	private TbUser tbUser;
	private Date createdate;
	private String state;
	private String name;
	private String type;
	private Date holdstartdate;
	private String address;
	private Integer num;
	private Float fee;
	private Date holdenddate;
	private Date enrollenddate;
	private String activityclass;
	private String imgpath;
	private String remark;
	private Set<TbEventanswer> tbEventanswers = new HashSet<TbEventanswer>(0);
	private Set<TbEventlog> tbEventlogs = new HashSet<TbEventlog>(0);
	private Integer enrollnum;
	private Integer unenrollnum;

	public TbEvent() {
	}

	public TbEvent(long baseid, Date createdate, Date holdstartdate, Date holdenddate, Date enrollenddate) {
		this.baseid = baseid;
		this.createdate = createdate;
		this.holdstartdate = holdstartdate;
		this.holdenddate = holdenddate;
		this.enrollenddate = enrollenddate;
	}

	public TbEvent(long baseid, TbUser tbUser, Date createdate, String state, String name, String type, Date holdstartdate, String address, Integer num, Float fee, Date holdenddate, Date enrollenddate, String activityclass, String imgpath, String remark, Set<TbEventanswer> tbEventanswers, Set<TbEventlog> tbEventlogs) {
		this.baseid = baseid;
		this.tbUser = tbUser;
		this.createdate = createdate;
		this.state = state;
		this.name = name;
		this.type = type;
		this.holdstartdate = holdstartdate;
		this.address = address;
		this.num = num;
		this.fee = fee;
		this.holdenddate = holdenddate;
		this.enrollenddate = enrollenddate;
		this.activityclass = activityclass;
		this.imgpath = imgpath;
		this.remark = remark;
		this.tbEventanswers = tbEventanswers;
		this.tbEventlogs = tbEventlogs;
	}

	@Id
	@Column(name = "baseid", unique = true, nullable = false)
	@GeneratedValue(generator = "eventtableGenerator")
	@GenericGenerator(name = "eventtableGenerator", strategy = "increment")
	public long getBaseid() {
		return this.baseid;
	}

	public void setBaseid(long baseid) {
		this.baseid = baseid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb__baseid")
	public TbUser getTbUser() {
		return this.tbUser;
	}

	public void setTbUser(TbUser tbUser) {
		this.tbUser = tbUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdate", nullable = false, length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Column(name = "state", length = 20)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type", length = 100)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "holdstartdate", nullable = false, length = 19)
	public Date getHoldstartdate() {
		return this.holdstartdate;
	}

	public void setHoldstartdate(Date holdstartdate) {
		this.holdstartdate = holdstartdate;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "num")
	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	@Column(name = "fee", precision = 12, scale = 0)
	public Float getFee() {
		return this.fee;
	}

	public void setFee(Float fee) {
		this.fee = fee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "holdenddate", nullable = false, length = 19)
	public Date getHoldenddate() {
		return this.holdenddate;
	}

	public void setHoldenddate(Date holdenddate) {
		this.holdenddate = holdenddate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "enrollenddate", nullable = false, length = 19)
	public Date getEnrollenddate() {
		return this.enrollenddate;
	}

	public void setEnrollenddate(Date enrollenddate) {
		this.enrollenddate = enrollenddate;
	}

	@Column(name = "activityclass", length = 200)
	public String getActivityclass() {
		return this.activityclass;
	}

	public void setActivityclass(String activityclass) {
		this.activityclass = activityclass;
	}

	@Column(name = "imgpath", length = 200)
	public String getImgpath() {
		return this.imgpath;
	}

	public void setImgpath(String imgpath) {
		this.imgpath = imgpath;
	}

	@Column(name = "remark", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbEvent")
	public Set<TbEventanswer> getTbEventanswers() {
		return this.tbEventanswers;
	}

	public void setTbEventanswers(Set<TbEventanswer> tbEventanswers) {
		this.tbEventanswers = tbEventanswers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbEvent")
	public Set<TbEventlog> getTbEventlogs() {
		return this.tbEventlogs;
	}

	public void setTbEventlogs(Set<TbEventlog> tbEventlogs) {
		this.tbEventlogs = tbEventlogs;
	}

	@Column(name = "enrollnum")
	public Integer getEnrollnum() {
		return enrollnum;
	}

	public void setEnrollnum(Integer enrollnum) {
		this.enrollnum = enrollnum;
	}

	@Column(name = "unenrollnum")
	public Integer getUnenrollnum() {
		return unenrollnum;
	}

	public void setUnenrollnum(Integer unenrollnum) {
		this.unenrollnum = unenrollnum;
	}

}
