package com.studentexchange.core.entity;

// Generated 2017-3-13 15:36:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * TbSecondhand generated by hbm2java
 */
@Entity
@Table(name = "tb_secondhand", catalog = "studentexchange")
public class TbSecondhand implements java.io.Serializable {

	private long baseid;
	private TbUser tbUser;
	private Date createdate;
	private String state;
	private Float price;
	private String content;
	private String name;
	private String phone;
	private String zipcode;
	private String address;
	private String city;
	private Set<TbSecondhandlog> tbSecondhandlogs = new HashSet<TbSecondhandlog>(0);

	public TbSecondhand() {
	}

	public TbSecondhand(long baseid, Date createdate) {
		this.baseid = baseid;
		this.createdate = createdate;
	}

	public TbSecondhand(long baseid, TbUser tbUser, Date createdate, String state, Float price, String content, String name, Set<TbSecondhandlog> tbSecondhandlogs) {
		this.baseid = baseid;
		this.tbUser = tbUser;
		this.createdate = createdate;
		this.state = state;
		this.price = price;
		this.content = content;
		this.name = name;
		this.tbSecondhandlogs = tbSecondhandlogs;
	}

	@Id
	@Column(name = "baseid", unique = true, nullable = false)
	@GeneratedValue(generator = "secondhandanswertableGenerator")
	@GenericGenerator(name = "secondhandanswertableGenerator", strategy = "increment")
	public long getBaseid() {
		return this.baseid;
	}

	public void setBaseid(long baseid) {
		this.baseid = baseid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb__baseid")
	public TbUser getTbUser() {
		return this.tbUser;
	}

	public void setTbUser(TbUser tbUser) {
		this.tbUser = tbUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdate", nullable = false, length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Column(name = "state", length = 20)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "price", precision = 12, scale = 0)
	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	@Column(name = "content", length = 500)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbSecondhand")
	public Set<TbSecondhandlog> getTbSecondhandlogs() {
		return this.tbSecondhandlogs;
	}

	public void setTbSecondhandlogs(Set<TbSecondhandlog> tbSecondhandlogs) {
		this.tbSecondhandlogs = tbSecondhandlogs;
	}

	@Column(name = "phone", length = 50)
	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "zipcode", length = 50)
	public String getZipcode() {
		return zipcode;
	}


	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "address", length = 500)
	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "city", length = 50)
	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}
	
	

}
