package com.studentexchange.core.entity;

// Generated 2017-3-13 15:36:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * TbSecondhandlog generated by hbm2java
 */
@Entity
@Table(name = "tb_secondhandlog", catalog = "studentexchange")
public class TbSecondhandlog implements java.io.Serializable {

	private long baseid;
	private TbUser tbUser;
	private TbSecondhand tbSecondhand;
	private Date createdate;
	private String state;
	private String remark;

	public TbSecondhandlog() {
	}

	public TbSecondhandlog(long baseid, Date createdate) {
		this.baseid = baseid;
		this.createdate = createdate;
	}

	public TbSecondhandlog(long baseid, TbUser tbUser, TbSecondhand tbSecondhand, Date createdate, String state) {
		this.baseid = baseid;
		this.tbUser = tbUser;
		this.tbSecondhand = tbSecondhand;
		this.createdate = createdate;
		this.state = state;
	}

	@Id
	@Column(name = "baseid", unique = true, nullable = false)
	@GeneratedValue(generator = "secondhandlogtableGenerator")
	@GenericGenerator(name = "secondhandlogtableGenerator", strategy = "increment")
	public long getBaseid() {
		return this.baseid;
	}

	public void setBaseid(long baseid) {
		this.baseid = baseid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb__baseid2")
	public TbUser getTbUser() {
		return this.tbUser;
	}

	public void setTbUser(TbUser tbUser) {
		this.tbUser = tbUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb__baseid")
	public TbSecondhand getTbSecondhand() {
		return this.tbSecondhand;
	}

	public void setTbSecondhand(TbSecondhand tbSecondhand) {
		this.tbSecondhand = tbSecondhand;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdate", nullable = false, length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Column(name = "state", length = 20)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}
	
	@Column(name = "remark", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
