package com.studentexchange.core.entity;

// Generated 2017-3-13 15:36:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * TbUser generated by hbm2java
 */
@Entity
@Table(name = "tb_user", catalog = "studentexchange")
public class TbUser implements java.io.Serializable {

	private long baseid;
	private Date createdate;
	private String state;
	private String name;
	private Integer age;
	private String address;
	private String phone;
	private String email;
	private String username;
	private String password;
	private Set<TbEventanswer> tbEventanswers = new HashSet<TbEventanswer>(0);
	private Set<TbSecondhandlog> tbSecondhandlogs = new HashSet<TbSecondhandlog>(0);
	private Set<TbSecondhand> tbSecondhands = new HashSet<TbSecondhand>(0);
	private Set<TbEventlog> tbEventlogs = new HashSet<TbEventlog>(0);
	private Set<TbEvent> tbEvents = new HashSet<TbEvent>(0);

	public TbUser() {
	}

	public TbUser(long baseid, Date createdate) {
		this.baseid = baseid;
		this.createdate = createdate;
	}

	public TbUser(long baseid, Date createdate, String state, String name, Integer age, String address, String phone, String email, String username, String password, Set<TbEventanswer> tbEventanswers, Set<TbSecondhandlog> tbSecondhandlogs, Set<TbSecondhand> tbSecondhands, Set<TbEventlog> tbEventlogs, Set<TbEvent> tbEvents) {
		this.baseid = baseid;
		this.createdate = createdate;
		this.state = state;
		this.name = name;
		this.age = age;
		this.address = address;
		this.phone = phone;
		this.email = email;
		this.username = username;
		this.password = password;
		this.tbEventanswers = tbEventanswers;
		this.tbSecondhandlogs = tbSecondhandlogs;
		this.tbSecondhands = tbSecondhands;
		this.tbEventlogs = tbEventlogs;
		this.tbEvents = tbEvents;
	}

	@Id
	@Column(name = "baseid", unique = true, nullable = false)
	@GeneratedValue(generator = "usertableGenerator")
	@GenericGenerator(name = "usertableGenerator", strategy = "increment")
	public long getBaseid() {
		return this.baseid;
	}

	public void setBaseid(long baseid) {
		this.baseid = baseid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdate", nullable = false, length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Column(name = "state", length = 20)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone", length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "username", length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbUser")
	public Set<TbEventanswer> getTbEventanswers() {
		return this.tbEventanswers;
	}

	public void setTbEventanswers(Set<TbEventanswer> tbEventanswers) {
		this.tbEventanswers = tbEventanswers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbUser")
	public Set<TbSecondhandlog> getTbSecondhandlogs() {
		return this.tbSecondhandlogs;
	}

	public void setTbSecondhandlogs(Set<TbSecondhandlog> tbSecondhandlogs) {
		this.tbSecondhandlogs = tbSecondhandlogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbUser")
	public Set<TbSecondhand> getTbSecondhands() {
		return this.tbSecondhands;
	}

	public void setTbSecondhands(Set<TbSecondhand> tbSecondhands) {
		this.tbSecondhands = tbSecondhands;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbUser")
	public Set<TbEventlog> getTbEventlogs() {
		return this.tbEventlogs;
	}

	public void setTbEventlogs(Set<TbEventlog> tbEventlogs) {
		this.tbEventlogs = tbEventlogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbUser")
	public Set<TbEvent> getTbEvents() {
		return this.tbEvents;
	}

	public void setTbEvents(Set<TbEvent> tbEvents) {
		this.tbEvents = tbEvents;
	}

}
